save_best: False

logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./sac_logs/
      verbose: False
      every_n_seconds: 10

algorithm:
      seed:
            train: 1
            eval: 99
            q: 123
            explorer: 456
            torch: 789

      nb_seeds: 1
      n_envs: 8
      n_steps_train: 32
      n_steps: 100_000
      max_grad_norm: 0.5
      buffer_size: 1e6
      batch_size: 256
      eval_interval: 2_000
      nb_evals: 10
      learning_starts: 10_000
      tau_target: 0.05
      discount_factor: 0.98
      entropy_mode: "auto" # "auto" or "fixed"
      init_entropy_coef: 2e-7

gym_env:
      env_name: CartPoleContinuous-v1

actor_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

critic_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

entropy_coef_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

policy_agent:
      classname: bbrl_cl.agents.SubspaceActionAgent
      hidden_size: 64
      input_dimension: nil
      output_dimension: nil
      start_steps: 0

      n_initial_anchors: 3
      dist_type: flat
      refresh_rate: 1.
      resampling_policy: False
      repeat_alpha: 100

critic_agent:
      classname: bbrl_cl.agents.agent.AlphaCritic
      hidden_size: 256
      obs_dimension: nil
      action_dimension: nil
      n_anchors: ${policy_agent.n_initial_anchors}

alpha_search:
      classname: bbrl_cl.algorithms.AlphaSearch
      params:
            n_estimations: 1024
            n_rollouts: 32
            seed: 0

visualization:
      num_points: 40