logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./sac_logs/
      verbose: False
      every_n_seconds: 10

subspace_algorithm:
      classname: bbrl_subspaces.algorithms.SAC
      name: "SAC"
      params:
            save_best: False
            algorithm:
                  seed:
                        train: 334
                        eval: 983
                        q: 123
                        explorer: 456
                        torch: 7
                  n_envs: 1
                  n_steps_train: 10
                  n_steps: 5e6
                  eval_interval: 2500
                  nb_evals: 2
                  buffer_size: 1e6
                  batch_size: 256
                  learning_starts: 10_000
                  tau_target: 0.005
                  max_grad_norm: 0.5
                  discount_factor: 0.9999
                  entropy_mode: "auto" # "auto" or "fixed"
                  init_entropy_coef: 0.2

            gym_env:
                  env_name: SwimmerBBRLEnv-v0

            actor_optimizer:
                  classname: torch.optim.Adam
                  lr: 0.006
                  eps: 5e-5

            critic_optimizer:
                  classname: torch.optim.Adam
                  lr: 0.006
                  eps: 5e-5

            entropy_coef_optimizer:
                  classname: torch.optim.Adam
                  lr: 0.003
                  eps: 1e-5


            policy_agent:
                  classname: bbrl_subspaces.agents.SubspaceActionAgent
                  hidden_size: 64
                  input_dimension: nil
                  output_dimension: nil
                  n_initial_anchors: 3
                  start_steps: 0
                  dist_type: flat
                  refresh_rate: 1.
                  resampling_policy: False
                  repeat_alpha: 100

            critic_agent:
                  classname: bbrl_subspaces.agents.AlphaCritic
                  hidden_size: 256
                  obs_dimension: nil
                  action_dimension: nil
                  n_anchors: ${subspace_algorithm.params.policy_agent.n_initial_anchors}

alpha_search:
      classname: bbrl_subspaces.algorithms.AlphaSearch
      n_rollouts: 32
      n_samples: 1024
      n_validation_steps: 200
      seed: 0

visualization:
      classname: bbrl_subspaces.visualization.SubspaceVisualizer
      algorithm_name: ${subspace_algorithm.name}
      env_name: ${subspace_algorithm.params.gym_env.env_name}
      num_points: 40
      interactive: False
      thresholds: [100_000, 300_000, 500_000]